apiVersion: apps/v1
kind: Deployment
metadata:
  name: education-support
  labels:
    app: education-support
spec:
  replicas: 1
  selector:
    matchLabels:
      app: education-support
  template:
    metadata:
      labels:
        app: education-support
    spec:
      containers:
        - name: education-support
          image: "username/education-support:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
