---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-management
  labels:
    app: project-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-management
  template:
    metadata:
      labels:
        app: project-management
    spec:
      containers:
        - name: project-management
          image: username/project-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coding-guide
  labels:
    app: coding-guide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coding-guide
  template:
    metadata:
      labels:
        app: coding-guide
    spec:
      containers:
        - name: coding-guide
          image: username/coding-guide:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: education-support
  labels:
    app: education-support
spec:
  replicas: 1
  selector:
    matchLabels:
      app: education-support
  template:
    metadata:
      labels:
        app: education-support
    spec:
      containers:
        - name: education-support
          image: username/education-support:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: project-management
  labels:
    app: project-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: project-management


---


apiVersion: v1
kind: Service
metadata:
  name: coding-guide
  labels:
    app: coding-guide
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: coding-guide


---


apiVersion: v1
kind: Service
metadata:
  name: education-support
  labels:
    app: education-support
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: education-support

