apiVersion: apps/v1
kind: Deployment
metadata:
  name: coding-guide
  labels:
    app: coding-guide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coding-guide
  template:
    metadata:
      labels:
        app: coding-guide
    spec:
      containers:
        - name: coding-guide
          image: "username/coding-guide:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
